import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import Footer from "./Components/Footer";
import Header from "./Components/Header";
import "./globals.css";
import ProgressBar from "./Components/Progress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <Script id="google-translate-init" strategy="afterInteractive">
          {`
            function googleTranslateElementInit() {
              new google.translate.TranslateElement({
                pageLanguage: 'en',
                includedLanguages: 'en,ru,uz',
                layout: google.translate.TranslateElement.InlineLayout.SIMPLE
              }, 'google_translate_element');
            }
          `}
        </Script>

        {/* Скрипт самого Google Translate */}
        <Script
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="afterInteractive"
        />
      
      <body id="custom_id"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProgressBar/>
        <Header/>
       
        {children}
        <Footer/>
      </body>
    </html>
  );
}
